data:
  rootdir: data
  dataset: UxLES
  high_res: 64
  upscale_factor: 4
  img_channels: 3

# Pretrained models
models:
  dwnld_vgg: False
  load: False
  save: False
  rootdir: models
  gen: gen.uxles.pth
  disc: disc.uxles.pth

# Training hyperparameters
train:
  learning_rate: 1.0e-4
  num_epochs: 200
  batch_size: 16
  num_workers: 4 # number of processes that gen batches in parallel

validation:
  kfold: True # If false Do not cross validate. Train with all training data.
  n_splits: 5 

figures:
  dir: figures
